-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "firstName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nationalIdHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nationalIdLast4" TEXT;
