/**
 * Iran administrative geography for NL intent routing.
 * Provinces (ostans) + county seats / major cities used in marketplace prompts.
 * Canonical city/province names are English identifiers; fa/en aliases match user text.
 */

export type IranProvince = {
  code: string;
  nameEn: string;
  nameFa: string;
  aliases?: string[];
};

export type IranCity = {
  nameEn: string;
  nameFa: string;
  provinceCode: string;
  aliases?: string[];
};

/** All 31 provinces of Iran. */
export const IRAN_PROVINCES: IranProvince[] = [
  { code: 'TE', nameEn: 'Tehran', nameFa: 'تهران', aliases: ['استان تهران'] },
  { code: 'AL', nameEn: 'Alborz', nameFa: 'البرز', aliases: ['استان البرز'] },
  { code: 'IS', nameEn: 'Isfahan', nameFa: 'اصفهان', aliases: ['استان اصفهان', 'Esfahan'] },
  { code: 'FA', nameEn: 'Fars', nameFa: 'فارس', aliases: ['استان فارس'] },
  { code: 'KZ', nameEn: 'Khuzestan', nameFa: 'خوزستان', aliases: ['استان خوزستان'] },
  { code: 'EA', nameEn: 'East Azerbaijan', nameFa: 'آذربایجان شرقی', aliases: ['آذربایجانشرقی', 'East Azarbaijan'] },
  { code: 'WA', nameEn: 'West Azerbaijan', nameFa: 'آذربایجان غربی', aliases: ['آذربایجانغربی', 'West Azarbaijan'] },
  { code: 'RK', nameEn: 'Razavi Khorasan', nameFa: 'خراسان رضوی', aliases: ['خراسانرضوی'] },
  { code: 'NK', nameEn: 'North Khorasan', nameFa: 'خراسان شمالی', aliases: ['خراسانشمالی'] },
  { code: 'SK', nameEn: 'South Khorasan', nameFa: 'خراسان جنوبی', aliases: ['خراسانجنوبی'] },
  { code: 'MN', nameEn: 'Mazandaran', nameFa: 'مازندران', aliases: ['استان مازندران'] },
  { code: 'GI', nameEn: 'Gilan', nameFa: 'گیلان', aliases: ['استان گیلان'] },
  { code: 'KD', nameEn: 'Kurdistan', nameFa: 'کردستان', aliases: ['استان کردستان'] },
  { code: 'KE', nameEn: 'Kerman', nameFa: 'کرمان', aliases: ['استان کرمان'] },
  { code: 'KS', nameEn: 'Kermanshah', nameFa: 'کرمانشاه', aliases: ['استان کرمانشاه'] },
  { code: 'GO', nameEn: 'Golestan', nameFa: 'گلستان', aliases: ['استان گلستان'] },
  { code: 'HM', nameEn: 'Hamadan', nameFa: 'همدان', aliases: ['استان همدان', 'Hamedan'] },
  { code: 'MK', nameEn: 'Markazi', nameFa: 'مرکزی', aliases: ['استان مرکزی'] },
  { code: 'LO', nameEn: 'Lorestan', nameFa: 'لرستان', aliases: ['استان لرستان'] },
  { code: 'SB', nameEn: 'Sistan and Baluchestan', nameFa: 'سیستان و بلوچستان', aliases: ['سیستان‌وبلوچستان', 'بلوچستان'] },
  { code: 'HG', nameEn: 'Hormozgan', nameFa: 'هرمزگان', aliases: ['استان هرمزگان'] },
  { code: 'YZ', nameEn: 'Yazd', nameFa: 'یزد', aliases: ['استان یزد'] },
  { code: 'ZN', nameEn: 'Zanjan', nameFa: 'زنجان', aliases: ['استان زنجان'] },
  { code: 'QZ', nameEn: 'Qazvin', nameFa: 'قزوین', aliases: ['استان قزوین'] },
  { code: 'QM', nameEn: 'Qom', nameFa: 'قم', aliases: ['استان قم'] },
  { code: 'SM', nameEn: 'Semnan', nameFa: 'سمنان', aliases: ['استان سمنان'] },
  { code: 'AR', nameEn: 'Ardabil', nameFa: 'اردبیل', aliases: ['استان اردبیل'] },
  { code: 'IL', nameEn: 'Ilam', nameFa: 'ایلام', aliases: ['استان ایلام'] },
  { code: 'BU', nameEn: 'Bushehr', nameFa: 'بوشهر', aliases: ['استان بوشهر'] },
  { code: 'KB', nameEn: 'Kohgiluyeh and Boyer-Ahmad', nameFa: 'کهگیلویه و بویراحمد', aliases: ['کهگیلویه', 'بویراحمد'] },
  { code: 'CB', nameEn: 'Chaharmahal and Bakhtiari', nameFa: 'چهارمحال و بختیاری', aliases: ['چهارمحال', 'بختیاری'] },
];

/**
 * County seats and major urban centers across all provinces.
 * Matching prefers longer FA aliases first (کرمانشاه before کرمان).
 */
export const IRAN_CITIES: IranCity[] = [
  // Tehran
  { nameEn: 'Tehran', nameFa: 'تهران', provinceCode: 'TE', aliases: ['Tehran'] },
  { nameEn: 'Rey', nameFa: 'شهرری', provinceCode: 'TE', aliases: ['شهر ری', 'Rey'] },
  { nameEn: 'Eslamshahr', nameFa: 'اسلامشهر', provinceCode: 'TE' },
  { nameEn: 'Shahriar', nameFa: 'شهریار', provinceCode: 'TE' },
  { nameEn: 'Malard', nameFa: 'ملارد', provinceCode: 'TE' },
  { nameEn: 'Pakdasht', nameFa: 'پاکدشت', provinceCode: 'TE' },
  { nameEn: 'Varamin', nameFa: 'ورامین', provinceCode: 'TE' },
  { nameEn: 'Damavand', nameFa: 'دماوند', provinceCode: 'TE' },
  { nameEn: 'Firuzkuh', nameFa: 'فیروزکوه', provinceCode: 'TE' },
  { nameEn: 'Pardis', nameFa: 'پردیس', provinceCode: 'TE' },
  { nameEn: 'Robat Karim', nameFa: 'رباط‌کریم', provinceCode: 'TE', aliases: ['رباط کریم'] },
  { nameEn: 'Qods', nameFa: 'قدس', provinceCode: 'TE', aliases: ['شهر قدس'] },
  { nameEn: 'Baharestan', nameFa: 'بهارستان', provinceCode: 'TE' },
  { nameEn: 'Pishva', nameFa: 'پیشوا', provinceCode: 'TE' },
  { nameEn: 'Hashtgerd', nameFa: 'هشتگرد', provinceCode: 'AL' },
  // Alborz
  { nameEn: 'Karaj', nameFa: 'کرج', provinceCode: 'AL', aliases: ['Karaj'] },
  { nameEn: 'Fardis', nameFa: 'فردیس', provinceCode: 'AL' },
  { nameEn: 'Mohammadshahr', nameFa: 'محمدشهر', provinceCode: 'AL' },
  { nameEn: 'Nazarabad', nameFa: 'نظرآباد', provinceCode: 'AL' },
  { nameEn: 'Taleqan', nameFa: 'طالقان', provinceCode: 'AL' },
  { nameEn: 'Eshtehard', nameFa: 'اشتهارد', provinceCode: 'AL' },
  { nameEn: 'Savojbolagh', nameFa: 'ساوجبلاغ', provinceCode: 'AL' },
  // Isfahan
  { nameEn: 'Isfahan', nameFa: 'اصفهان', provinceCode: 'IS', aliases: ['Esfahan', 'Isfahan'] },
  { nameEn: 'Kashan', nameFa: 'کاشان', provinceCode: 'IS', aliases: ['Kashan'] },
  { nameEn: 'Najafabad', nameFa: 'نجف‌آباد', provinceCode: 'IS', aliases: ['نجف آباد'] },
  { nameEn: 'Khomeinishahr', nameFa: 'خمینی‌شهر', provinceCode: 'IS', aliases: ['خمینی شهر'] },
  { nameEn: 'Shahinshahr', nameFa: 'شاهین‌شهر', provinceCode: 'IS', aliases: ['شاهین شهر'] },
  { nameEn: 'Fooladshahr', nameFa: 'فولادشهر', provinceCode: 'IS' },
  { nameEn: 'Mobarakeh', nameFa: 'مبارکه', provinceCode: 'IS' },
  { nameEn: 'Falavarjan', nameFa: 'فلاورجان', provinceCode: 'IS' },
  { nameEn: 'Natanz', nameFa: 'نطنز', provinceCode: 'IS' },
  { nameEn: 'Ardestan', nameFa: 'اردستان', provinceCode: 'IS' },
  { nameEn: 'Nain', nameFa: 'نایین', provinceCode: 'IS', aliases: ['نائین'] },
  { nameEn: 'Semirom', nameFa: 'سمیرم', provinceCode: 'IS' },
  { nameEn: 'Shahreza', nameFa: 'شهرضا', provinceCode: 'IS' },
  { nameEn: 'Golpayegan', nameFa: 'گلپایگان', provinceCode: 'IS' },
  { nameEn: 'Khansar', nameFa: 'خوانسار', provinceCode: 'IS' },
  { nameEn: 'Aran va Bidgol', nameFa: 'آران و بیدگل', provinceCode: 'IS', aliases: ['آران‌وبیدگل'] },
  { nameEn: 'Lenjan', nameFa: 'لنجان', provinceCode: 'IS' },
  { nameEn: 'Tiran', nameFa: 'تیران', provinceCode: 'IS' },
  // Fars
  { nameEn: 'Shiraz', nameFa: 'شیراز', provinceCode: 'FA', aliases: ['Shiraz'] },
  { nameEn: 'Marvdasht', nameFa: 'مرودشت', provinceCode: 'FA' },
  { nameEn: 'Jahrom', nameFa: 'جهرم', provinceCode: 'FA' },
  { nameEn: 'Fasa', nameFa: 'فسا', provinceCode: 'FA' },
  { nameEn: 'Kazerun', nameFa: 'کازرون', provinceCode: 'FA' },
  { nameEn: 'Lar', nameFa: 'لار', provinceCode: 'FA', aliases: ['لارستان'] },
  { nameEn: 'Abadeh', nameFa: 'آباده', provinceCode: 'FA' },
  { nameEn: 'Neyriz', nameFa: 'نی‌ریز', provinceCode: 'FA', aliases: ['نیریز'] },
  { nameEn: 'Darab', nameFa: 'داراب', provinceCode: 'FA' },
  { nameEn: 'Firuzabad', nameFa: 'فیروزآباد', provinceCode: 'FA' },
  { nameEn: 'Estahban', nameFa: 'استهبان', provinceCode: 'FA' },
  { nameEn: 'Lamerd', nameFa: 'لامرد', provinceCode: 'FA' },
  { nameEn: 'Gerash', nameFa: 'گراش', provinceCode: 'FA' },
  // Razavi Khorasan
  { nameEn: 'Mashhad', nameFa: 'مشهد', provinceCode: 'RK', aliases: ['Mashhad'] },
  { nameEn: 'Neyshabur', nameFa: 'نیشابور', provinceCode: 'RK', aliases: ['Nishapur'] },
  { nameEn: 'Sabzevar', nameFa: 'سبزوار', provinceCode: 'RK' },
  { nameEn: 'Torbat-e Heydarieh', nameFa: 'تربت حیدریه', provinceCode: 'RK', aliases: ['تربت‌حیدریه'] },
  { nameEn: 'Quchan', nameFa: 'قوچان', provinceCode: 'RK' },
  { nameEn: 'Torbat-e Jam', nameFa: 'تربت جام', provinceCode: 'RK', aliases: ['تربت‌جام'] },
  { nameEn: 'Kashmar', nameFa: 'کاشمر', provinceCode: 'RK' },
  { nameEn: 'Gonabad', nameFa: 'گناباد', provinceCode: 'RK' },
  { nameEn: 'Chenaran', nameFa: 'چناران', provinceCode: 'RK' },
  { nameEn: 'Dargaz', nameFa: 'درگز', provinceCode: 'RK' },
  { nameEn: 'Taybad', nameFa: 'تایباد', provinceCode: 'RK' },
  { nameEn: 'Sarakhs', nameFa: 'سرخس', provinceCode: 'RK' },
  // East Azerbaijan
  { nameEn: 'Tabriz', nameFa: 'تبریز', provinceCode: 'EA', aliases: ['Tabriz'] },
  { nameEn: 'Maragheh', nameFa: 'مراغه', provinceCode: 'EA' },
  { nameEn: 'Marand', nameFa: 'مرند', provinceCode: 'EA' },
  { nameEn: 'Ahar', nameFa: 'اهر', provinceCode: 'EA' },
  { nameEn: 'Mianeh', nameFa: 'میانه', provinceCode: 'EA' },
  { nameEn: 'Bonab', nameFa: 'بناب', provinceCode: 'EA' },
  { nameEn: 'Sarab', nameFa: 'سراب', provinceCode: 'EA' },
  { nameEn: 'Azarshahr', nameFa: 'آذرشهر', provinceCode: 'EA' },
  { nameEn: 'Shabestar', nameFa: 'شبستر', provinceCode: 'EA' },
  { nameEn: 'Jolfa', nameFa: 'جلفا', provinceCode: 'EA' },
  // West Azerbaijan
  { nameEn: 'Urmia', nameFa: 'ارومیه', provinceCode: 'WA', aliases: ['Urmia', 'Orumiyeh'] },
  { nameEn: 'Khoy', nameFa: 'خوی', provinceCode: 'WA' },
  { nameEn: 'Mahabad', nameFa: 'مهاباد', provinceCode: 'WA' },
  { nameEn: 'Miandoab', nameFa: 'میاندوآب', provinceCode: 'WA' },
  { nameEn: 'Boukan', nameFa: 'بوکان', provinceCode: 'WA' },
  { nameEn: 'Salmas', nameFa: 'سلماس', provinceCode: 'WA' },
  { nameEn: 'Piranshahr', nameFa: 'پیرانشهر', provinceCode: 'WA' },
  { nameEn: 'Oshnavieh', nameFa: 'اشنویه', provinceCode: 'WA' },
  { nameEn: 'Maku', nameFa: 'ماکو', provinceCode: 'WA' },
  { nameEn: 'Sardasht', nameFa: 'سردشت', provinceCode: 'WA' },
  { nameEn: 'Takab', nameFa: 'تکاب', provinceCode: 'WA' },
  // Khuzestan
  { nameEn: 'Ahvaz', nameFa: 'اهواز', provinceCode: 'KZ', aliases: ['Ahvaz', 'Ahwaz'] },
  { nameEn: 'Abadan', nameFa: 'آبادان', provinceCode: 'KZ' },
  { nameEn: 'Khorramshahr', nameFa: 'خرمشهر', provinceCode: 'KZ' },
  { nameEn: 'Dezful', nameFa: 'دزفول', provinceCode: 'KZ' },
  { nameEn: 'Andimeshk', nameFa: 'اندیمشک', provinceCode: 'KZ' },
  { nameEn: 'Bandar-e Mahshahr', nameFa: 'ماهشهر', provinceCode: 'KZ', aliases: ['بندر ماهشهر', 'Mahshahr'] },
  { nameEn: 'Behbahan', nameFa: 'بهبهان', provinceCode: 'KZ' },
  { nameEn: 'Shushtar', nameFa: 'شوشتر', provinceCode: 'KZ' },
  { nameEn: 'Izeh', nameFa: 'ایذه', provinceCode: 'KZ' },
  { nameEn: 'Masjed Soleyman', nameFa: 'مسجدسلیمان', provinceCode: 'KZ', aliases: ['مسجد سلیمان'] },
  { nameEn: 'Ramhormoz', nameFa: 'رامهرمز', provinceCode: 'KZ' },
  { nameEn: 'Shush', nameFa: 'شوش', provinceCode: 'KZ' },
  { nameEn: 'Omidiyeh', nameFa: 'امیدیه', provinceCode: 'KZ' },
  { nameEn: 'Gotvand', nameFa: 'گتوند', provinceCode: 'KZ' },
  // Mazandaran
  { nameEn: 'Sari', nameFa: 'ساری', provinceCode: 'MN', aliases: ['Sari'] },
  { nameEn: 'Amol', nameFa: 'آمل', provinceCode: 'MN' },
  { nameEn: 'Babol', nameFa: 'بابل', provinceCode: 'MN' },
  { nameEn: 'Qaemshahr', nameFa: 'قائم‌شهر', provinceCode: 'MN', aliases: ['قائم شهر', 'قائمشهر'] },
  { nameEn: 'Chalus', nameFa: 'چالوس', provinceCode: 'MN' },
  { nameEn: 'Nowshahr', nameFa: 'نوشهر', provinceCode: 'MN' },
  { nameEn: 'Tonekabon', nameFa: 'تنکابن', provinceCode: 'MN' },
  { nameEn: 'Ramsar', nameFa: 'رامسر', provinceCode: 'MN' },
  { nameEn: 'Behshahr', nameFa: 'بهشهر', provinceCode: 'MN' },
  { nameEn: 'Neka', nameFa: 'نکا', provinceCode: 'MN' },
  { nameEn: 'Mahmudabad', nameFa: 'محمودآباد', provinceCode: 'MN' },
  { nameEn: 'Babolsar', nameFa: 'بابلسر', provinceCode: 'MN' },
  { nameEn: 'Juybar', nameFa: 'جویبار', provinceCode: 'MN' },
  // Gilan
  { nameEn: 'Rasht', nameFa: 'رشت', provinceCode: 'GI', aliases: ['Rasht'] },
  { nameEn: 'Bandar-e Anzali', nameFa: 'بندر انزلی', provinceCode: 'GI', aliases: ['انزلی', 'Anzali'] },
  { nameEn: 'Lahijan', nameFa: 'لاهیجان', provinceCode: 'GI' },
  { nameEn: 'Langarud', nameFa: 'لنگرود', provinceCode: 'GI' },
  { nameEn: 'Sowmeeh Sara', nameFa: 'صومعه‌سرا', provinceCode: 'GI', aliases: ['صومعه سرا'] },
  { nameEn: 'Astara', nameFa: 'آستارا', provinceCode: 'GI' },
  { nameEn: 'Talesh', nameFa: 'تالش', provinceCode: 'GI', aliases: ['هشتپر'] },
  { nameEn: 'Rudsar', nameFa: 'رودسر', provinceCode: 'GI' },
  { nameEn: 'Fuman', nameFa: 'فومن', provinceCode: 'GI' },
  { nameEn: 'Shaft', nameFa: 'شفت', provinceCode: 'GI' },
  { nameEn: 'Rudbar', nameFa: 'رودبار', provinceCode: 'GI' },
  { nameEn: 'Astaneh-ye Ashrafiyeh', nameFa: 'آستانه اشرفیه', provinceCode: 'GI' },
  // Kerman
  { nameEn: 'Kerman', nameFa: 'کرمان', provinceCode: 'KE', aliases: ['Kerman'] },
  { nameEn: 'Sirjan', nameFa: 'سیرجان', provinceCode: 'KE' },
  { nameEn: 'Rafsanjan', nameFa: 'رفسنجان', provinceCode: 'KE' },
  { nameEn: 'Jiroft', nameFa: 'جیرفت', provinceCode: 'KE' },
  { nameEn: 'Bam', nameFa: 'بم', provinceCode: 'KE' },
  { nameEn: 'Zarand', nameFa: 'زرند', provinceCode: 'KE' },
  { nameEn: 'Kahnuj', nameFa: 'کهنوج', provinceCode: 'KE' },
  { nameEn: 'Shahr-e Babak', nameFa: 'شهربابک', provinceCode: 'KE', aliases: ['شهر بابک'] },
  // Sistan & Baluchestan
  { nameEn: 'Zahedan', nameFa: 'زاهدان', provinceCode: 'SB', aliases: ['Zahedan'] },
  { nameEn: 'Zabol', nameFa: 'زابل', provinceCode: 'SB' },
  { nameEn: 'Chabahar', nameFa: 'چابهار', provinceCode: 'SB' },
  { nameEn: 'Iranshahr', nameFa: 'ایرانشهر', provinceCode: 'SB' },
  { nameEn: 'Saravan', nameFa: 'سراوان', provinceCode: 'SB' },
  { nameEn: 'Khash', nameFa: 'خاش', provinceCode: 'SB' },
  { nameEn: 'Konarak', nameFa: 'کنارک', provinceCode: 'SB' },
  // Hormozgan
  { nameEn: 'Bandar Abbas', nameFa: 'بندرعباس', provinceCode: 'HG', aliases: ['بندر عباس', 'Bandar Abbas'] },
  { nameEn: 'Minab', nameFa: 'میناب', provinceCode: 'HG' },
  { nameEn: 'Qeshm', nameFa: 'قشم', provinceCode: 'HG', aliases: ['Qeshm'] },
  { nameEn: 'Bandar Lengeh', nameFa: 'بندر لنگه', provinceCode: 'HG', aliases: ['لنگه'] },
  { nameEn: 'Kish', nameFa: 'کیش', provinceCode: 'HG', aliases: ['Kish'] },
  { nameEn: 'Hajiabad', nameFa: 'حاجی‌آباد', provinceCode: 'HG', aliases: ['حاجی آباد'] },
  { nameEn: 'Rudan', nameFa: 'رودان', provinceCode: 'HG' },
  // Kermanshah
  { nameEn: 'Kermanshah', nameFa: 'کرمانشاه', provinceCode: 'KS', aliases: ['Kermanshah'] },
  { nameEn: 'Eslamabad-e Gharb', nameFa: 'اسلام‌آباد غرب', provinceCode: 'KS', aliases: ['اسلام آباد غرب'] },
  { nameEn: 'Javanrud', nameFa: 'جوانرود', provinceCode: 'KS' },
  { nameEn: 'Kangavar', nameFa: 'کنگاور', provinceCode: 'KS' },
  { nameEn: 'Sonqor', nameFa: 'سنقر', provinceCode: 'KS' },
  { nameEn: 'Sahneh', nameFa: 'صحنه', provinceCode: 'KS' },
  { nameEn: 'Paveh', nameFa: 'پاوه', provinceCode: 'KS' },
  { nameEn: 'Sarpol-e Zahab', nameFa: 'سرپل ذهاب', provinceCode: 'KS', aliases: ['سرپل‌ذهاب'] },
  // Lorestan
  { nameEn: 'Khorramabad', nameFa: 'خرم‌آباد', provinceCode: 'LO', aliases: ['خرم آباد', 'Khorramabad'] },
  { nameEn: 'Borujerd', nameFa: 'بروجرد', provinceCode: 'LO' },
  { nameEn: 'Dorud', nameFa: 'دورود', provinceCode: 'LO' },
  { nameEn: 'Aligudarz', nameFa: 'الیگودرز', provinceCode: 'LO' },
  { nameEn: 'Kuhdasht', nameFa: 'کوهدشت', provinceCode: 'LO' },
  { nameEn: 'Nurabad', nameFa: 'نورآباد', provinceCode: 'LO' },
  { nameEn: 'Azna', nameFa: 'ازنا', provinceCode: 'LO' },
  { nameEn: 'Pol-e Dokhtar', nameFa: 'پلدختر', provinceCode: 'LO', aliases: ['پل دختر'] },
  // Hamadan
  { nameEn: 'Hamedan', nameFa: 'همدان', provinceCode: 'HM', aliases: ['Hamadan', 'Hamedan'] },
  { nameEn: 'Malayer', nameFa: 'ملایر', provinceCode: 'HM' },
  { nameEn: 'Nahavand', nameFa: 'نهاوند', provinceCode: 'HM' },
  { nameEn: 'Asadabad', nameFa: 'اسدآباد', provinceCode: 'HM' },
  { nameEn: 'Tuyserkan', nameFa: 'تویسرکان', provinceCode: 'HM' },
  { nameEn: 'Kabudarahang', nameFa: 'کبودرآهنگ', provinceCode: 'HM' },
  { nameEn: 'Razan', nameFa: 'رزن', provinceCode: 'HM' },
  // Markazi
  { nameEn: 'Arak', nameFa: 'اراک', provinceCode: 'MK', aliases: ['Arak'] },
  { nameEn: 'Saveh', nameFa: 'ساوه', provinceCode: 'MK' },
  { nameEn: 'Khomein', nameFa: 'خمین', provinceCode: 'MK' },
  { nameEn: 'Mahallat', nameFa: 'محلات', provinceCode: 'MK' },
  { nameEn: 'Delijan', nameFa: 'دلیجان', provinceCode: 'MK' },
  { nameEn: 'Tafresh', nameFa: 'تفرش', provinceCode: 'MK' },
  { nameEn: 'Ashtian', nameFa: 'آشتیان', provinceCode: 'MK' },
  { nameEn: 'Shazand', nameFa: 'شازند', provinceCode: 'MK' },
  // Qazvin
  { nameEn: 'Qazvin', nameFa: 'قزوین', provinceCode: 'QZ', aliases: ['Qazvin'] },
  { nameEn: 'Takestan', nameFa: 'تاکستان', provinceCode: 'QZ' },
  { nameEn: 'Alvand', nameFa: 'الوند', provinceCode: 'QZ' },
  { nameEn: 'Abyek', nameFa: 'آبیک', provinceCode: 'QZ' },
  { nameEn: 'Buin Zahra', nameFa: 'بوئین‌زهرا', provinceCode: 'QZ', aliases: ['بوئین زهرا'] },
  // Qom
  { nameEn: 'Qom', nameFa: 'قم', provinceCode: 'QM', aliases: ['Qom'] },
  // Yazd
  { nameEn: 'Yazd', nameFa: 'یزد', provinceCode: 'YZ', aliases: ['Yazd'] },
  { nameEn: 'Ardakan', nameFa: 'اردکان', provinceCode: 'YZ' },
  { nameEn: 'Meybod', nameFa: 'میبد', provinceCode: 'YZ' },
  { nameEn: 'Bafq', nameFa: 'بافق', provinceCode: 'YZ' },
  { nameEn: 'Mehriz', nameFa: 'مهریز', provinceCode: 'YZ' },
  { nameEn: 'Taft', nameFa: 'تفت', provinceCode: 'YZ' },
  { nameEn: 'Abarkuh', nameFa: 'ابرکوه', provinceCode: 'YZ' },
  // Zanjan
  { nameEn: 'Zanjan', nameFa: 'زنجان', provinceCode: 'ZN', aliases: ['Zanjan'] },
  { nameEn: 'Abhar', nameFa: 'ابهر', provinceCode: 'ZN' },
  { nameEn: 'Khorramdarreh', nameFa: 'خرمدره', provinceCode: 'ZN' },
  { nameEn: 'Qeydar', nameFa: 'قیدار', provinceCode: 'ZN' },
  { nameEn: 'Tarom', nameFa: 'طارم', provinceCode: 'ZN' },
  // Semnan
  { nameEn: 'Semnan', nameFa: 'سمنان', provinceCode: 'SM', aliases: ['Semnan'] },
  { nameEn: 'Shahrud', nameFa: 'شاهرود', provinceCode: 'SM', aliases: ['Shahroud'] },
  { nameEn: 'Damghan', nameFa: 'دامغان', provinceCode: 'SM' },
  { nameEn: 'Garmsar', nameFa: 'گرمسار', provinceCode: 'SM' },
  { nameEn: 'Mehdishahr', nameFa: 'مهدی‌شهر', provinceCode: 'SM', aliases: ['مهدیشهر'] },
  // Golestan
  { nameEn: 'Gorgan', nameFa: 'گرگان', provinceCode: 'GO', aliases: ['Gorgan'] },
  { nameEn: 'Gonbad-e Kavus', nameFa: 'گنبد کاووس', provinceCode: 'GO', aliases: ['گنبدکاووس'] },
  { nameEn: 'Aliabad-e Katul', nameFa: 'علی‌آباد کتول', provinceCode: 'GO', aliases: ['علی آباد'] },
  { nameEn: 'Bandar Torkaman', nameFa: 'بندر ترکمن', provinceCode: 'GO' },
  { nameEn: 'Aqqala', nameFa: 'آق‌قلا', provinceCode: 'GO', aliases: ['آق قلا'] },
  { nameEn: 'Kalaleh', nameFa: 'کلاله', provinceCode: 'GO' },
  { nameEn: 'Minudasht', nameFa: 'مینودشت', provinceCode: 'GO' },
  { nameEn: 'Kordkuy', nameFa: 'کردکوی', provinceCode: 'GO' },
  // Ardabil
  { nameEn: 'Ardabil', nameFa: 'اردبیل', provinceCode: 'AR', aliases: ['Ardabil'] },
  { nameEn: 'Parsabad', nameFa: 'پارس‌آباد', provinceCode: 'AR', aliases: ['پارس آباد'] },
  { nameEn: 'Meshginshahr', nameFa: 'مشگین‌شهر', provinceCode: 'AR', aliases: ['مشگین شهر'] },
  { nameEn: 'Khalkhal', nameFa: 'خلخال', provinceCode: 'AR' },
  { nameEn: 'Germi', nameFa: 'گرمی', provinceCode: 'AR' },
  { nameEn: 'Bilehsavar', nameFa: 'بیله‌سوار', provinceCode: 'AR', aliases: ['بیله سوار'] },
  // Kurdistan
  { nameEn: 'Sanandaj', nameFa: 'سنندج', provinceCode: 'KD', aliases: ['Sanandaj'] },
  { nameEn: 'Saqqez', nameFa: 'سقز', provinceCode: 'KD' },
  { nameEn: 'Marivan', nameFa: 'مریوان', provinceCode: 'KD' },
  { nameEn: 'Baneh', nameFa: 'بانه', provinceCode: 'KD' },
  { nameEn: 'Qorveh', nameFa: 'قروه', provinceCode: 'KD' },
  { nameEn: 'Bijar', nameFa: 'بیجار', provinceCode: 'KD' },
  { nameEn: 'Divandarreh', nameFa: 'دیواندره', provinceCode: 'KD' },
  { nameEn: 'Kamyaran', nameFa: 'کامیاران', provinceCode: 'KD' },
  // Ilam
  { nameEn: 'Ilam', nameFa: 'ایلام', provinceCode: 'IL', aliases: ['Ilam'] },
  { nameEn: 'Dehloran', nameFa: 'دهلران', provinceCode: 'IL' },
  { nameEn: 'Eyvan', nameFa: 'ایوان', provinceCode: 'IL' },
  { nameEn: 'Abdanan', nameFa: 'آبدانان', provinceCode: 'IL' },
  { nameEn: 'Mehran', nameFa: 'مهران', provinceCode: 'IL' },
  { nameEn: 'Darreh Shahr', nameFa: 'دره‌شهر', provinceCode: 'IL', aliases: ['دره شهر'] },
  // Bushehr
  { nameEn: 'Bushehr', nameFa: 'بوشهر', provinceCode: 'BU', aliases: ['Bushehr'] },
  { nameEn: 'Borazjan', nameFa: 'برازجان', provinceCode: 'BU' },
  { nameEn: 'Bandar Genaveh', nameFa: 'گناوه', provinceCode: 'BU', aliases: ['بندر گناوه'] },
  { nameEn: 'Bandar Kangan', nameFa: 'کنگان', provinceCode: 'BU' },
  { nameEn: 'Asaluyeh', nameFa: 'عسلویه', provinceCode: 'BU' },
  { nameEn: 'Khormuj', nameFa: 'خورموج', provinceCode: 'BU' },
  { nameEn: 'Dayyer', nameFa: 'دیر', provinceCode: 'BU' },
  // Kohgiluyeh and Boyer-Ahmad
  { nameEn: 'Yasuj', nameFa: 'یاسوج', provinceCode: 'KB', aliases: ['Yasuj'] },
  { nameEn: 'Dogonbadan', nameFa: 'دوگنبدان', provinceCode: 'KB', aliases: ['گچساران', 'Gachsaran'] },
  { nameEn: 'Dehdasht', nameFa: 'دهدشت', provinceCode: 'KB' },
  // Chaharmahal and Bakhtiari
  { nameEn: 'Shahrekord', nameFa: 'شهرکرد', provinceCode: 'CB', aliases: ['شهر کرد', 'Shahrekord'] },
  { nameEn: 'Borujen', nameFa: 'بروجن', provinceCode: 'CB' },
  { nameEn: 'Lordegan', nameFa: 'لردگان', provinceCode: 'CB' },
  { nameEn: 'Farrokhshahr', nameFa: 'فرخ‌شهر', provinceCode: 'CB', aliases: ['فرخشهر'] },
  { nameEn: 'Farsan', nameFa: 'فارسان', provinceCode: 'CB' },
  // North Khorasan
  { nameEn: 'Bojnurd', nameFa: 'بجنورد', provinceCode: 'NK', aliases: ['Bojnurd'] },
  { nameEn: 'Shirvan', nameFa: 'شیروان', provinceCode: 'NK' },
  { nameEn: 'Esfarayen', nameFa: 'اسفراین', provinceCode: 'NK' },
  { nameEn: 'Jajarm', nameFa: 'جاجرم', provinceCode: 'NK' },
  { nameEn: 'Faruj', nameFa: 'فاروج', provinceCode: 'NK' },
  // South Khorasan
  { nameEn: 'Birjand', nameFa: 'بیرجند', provinceCode: 'SK', aliases: ['Birjand'] },
  { nameEn: 'Qaen', nameFa: 'قاین', provinceCode: 'SK', aliases: ['قاینات'] },
  { nameEn: 'Ferdows', nameFa: 'فردوس', provinceCode: 'SK' },
  { nameEn: 'Tabas', nameFa: 'طبس', provinceCode: 'SK' },
  { nameEn: 'Nehbandan', nameFa: 'نهبندان', provinceCode: 'SK' },
  // Expanded county seats / satellite towns
  { nameEn: 'Hashtgerd New Town', nameFa: 'شهر جدید هشتگرد', provinceCode: 'AL' },
  { nameEn: 'Parand', nameFa: 'پرند', provinceCode: 'TE' },
  { nameEn: 'Andisheh', nameFa: 'اندیشه', provinceCode: 'TE' },
  { nameEn: 'Bumehen', nameFa: 'بومهن', provinceCode: 'TE' },
  { nameEn: 'Javadabad', nameFa: 'جوادآباد', provinceCode: 'TE' },
  { nameEn: 'Zarinshahr', nameFa: 'زرین‌شهر', provinceCode: 'IS' },
  { nameEn: 'Dolatabad', nameFa: 'دولت‌آباد', provinceCode: 'IS' },
  { nameEn: 'Khorasgan', nameFa: 'خوراسگان', provinceCode: 'IS' },
  { nameEn: 'Chadegan', nameFa: 'چادگان', provinceCode: 'IS' },
  { nameEn: 'Fereydunshahr', nameFa: 'فریدون‌شهر', provinceCode: 'IS' },
  { nameEn: 'Nurabad Mamasani', nameFa: 'نورآباد ممسنی', provinceCode: 'FA' },
  { nameEn: 'Sepidan', nameFa: 'سپیدان', provinceCode: 'FA' },
  { nameEn: 'Zarqan', nameFa: 'زرقان', provinceCode: 'FA' },
  { nameEn: 'Kavar', nameFa: 'کوار', provinceCode: 'FA' },
  { nameEn: 'Sarvestan', nameFa: 'سروستان', provinceCode: 'FA' },
  { nameEn: 'Fariman', nameFa: 'فریمان', provinceCode: 'RK' },
  { nameEn: 'Bardaskan', nameFa: 'بردسکن', provinceCode: 'RK' },
  { nameEn: 'Khalilabad', nameFa: 'خلیل‌آباد', provinceCode: 'RK' },
  { nameEn: 'Roshtkhar', nameFa: 'رشتخوار', provinceCode: 'RK' },
  { nameEn: 'Bajestan', nameFa: 'بجستان', provinceCode: 'RK' },
  { nameEn: 'Hendijan', nameFa: 'هندیجان', provinceCode: 'KZ' },
  { nameEn: 'Shadegan', nameFa: 'شادگان', provinceCode: 'KZ' },
  { nameEn: 'Ramshir', nameFa: 'رامشیر', provinceCode: 'KZ' },
  { nameEn: 'Haftkel', nameFa: 'هفتکل', provinceCode: 'KZ' },
  { nameEn: 'Lali', nameFa: 'لالی', provinceCode: 'KZ' },
  { nameEn: 'Freydunkenar', nameFa: 'فریدونکنار', provinceCode: 'MN' },
  { nameEn: 'Kelarabad', nameFa: 'کلارآباد', provinceCode: 'MN' },
  { nameEn: 'Abbasabad', nameFa: 'عباس‌آباد', provinceCode: 'MN' },
  { nameEn: 'Galugah', nameFa: 'گلوگاه', provinceCode: 'MN' },
  { nameEn: 'Savadkuh', nameFa: 'سوادکوه', provinceCode: 'MN' },
  { nameEn: 'Masal', nameFa: 'ماسال', provinceCode: 'GI' },
  { nameEn: 'Rezvanshahr', nameFa: 'رضوانشهر', provinceCode: 'GI' },
  { nameEn: 'Amlash', nameFa: 'املش', provinceCode: 'GI' },
  { nameEn: 'Siahkal', nameFa: 'سیاهکل', provinceCode: 'GI' },
  { nameEn: 'Kuchesfahan', nameFa: 'کوچصفهان', provinceCode: 'GI' },
  { nameEn: 'Bardsir', nameFa: 'بردسیر', provinceCode: 'KE' },
  { nameEn: 'Anbarabad', nameFa: 'عنبرآباد', provinceCode: 'KE' },
  { nameEn: 'Manujan', nameFa: 'منوجان', provinceCode: 'KE' },
  { nameEn: 'Ravar', nameFa: 'راور', provinceCode: 'KE' },
  { nameEn: 'Fahraj', nameFa: 'فهرج', provinceCode: 'KE' },
  { nameEn: 'Pakdasht Industrial', nameFa: 'شهرک صنعتی پاکدشت', provinceCode: 'TE' },
  { nameEn: 'Shahriar Industrial', nameFa: 'شهرک صنعتی شهریار', provinceCode: 'TE' },
  { nameEn: 'Najafabad Industrial', nameFa: 'شهرک صنعتی نجف‌آباد', provinceCode: 'IS' },
  { nameEn: 'Mahshahr Port', nameFa: 'بندر امام خمینی', provinceCode: 'KZ' },
  { nameEn: 'Bandar Imam Khomeini', nameFa: 'بندرامام', provinceCode: 'KZ' },
  { nameEn: 'Asaluyeh Port', nameFa: 'بندر عسلویه', provinceCode: 'BU' },
  { nameEn: 'Chabahar Free Zone', nameFa: 'منطقه آزاد چابهار', provinceCode: 'SB' },
  { nameEn: 'Aras Free Zone', nameFa: 'منطقه آزاد ارس', provinceCode: 'EA' },
  { nameEn: 'Anzali Free Zone', nameFa: 'منطقه آزاد انزلی', provinceCode: 'GI' },
  { nameEn: 'Qeshm Free Zone', nameFa: 'منطقه آزاد قشم', provinceCode: 'HG' },
  { nameEn: 'Kish Free Zone', nameFa: 'منطقه آزاد کیش', provinceCode: 'HG' },
  { nameEn: 'Eqlid', nameFa: 'اقلید', provinceCode: 'FA' },
  { nameEn: 'Pasargad', nameFa: 'پاسارگاد', provinceCode: 'FA' },
  { nameEn: 'Khorrambid', nameFa: 'خرم‌بید', provinceCode: 'FA' },
  { nameEn: 'Bavanat', nameFa: 'بوانات', provinceCode: 'FA' },
  { nameEn: 'Kharameh', nameFa: 'خرامه', provinceCode: 'FA' },
  { nameEn: 'Mahdasht', nameFa: 'ماهدشت', provinceCode: 'AL' },
  { nameEn: 'Garmdareh', nameFa: 'گرمدره', provinceCode: 'AL' },
  { nameEn: 'Meshkin Dasht', nameFa: 'مشکین‌دشت', provinceCode: 'AL' },
  { nameEn: 'Kamalshahr', nameFa: 'کمال‌شهر', provinceCode: 'AL' },
  { nameEn: 'Mohammadiyeh', nameFa: 'محمدیه', provinceCode: 'QZ' },
  { nameEn: 'Eqbaliyeh', nameFa: 'اقبالیه', provinceCode: 'QZ' },
  { nameEn: 'Shal', nameFa: 'شال', provinceCode: 'QZ' },
  { nameEn: 'Avaj', nameFa: 'آوج', provinceCode: 'QZ' },
  { nameEn: 'Damavand Absard', nameFa: 'آبسرد', provinceCode: 'TE' },
  { nameEn: 'Lavasan', nameFa: 'لواسان', provinceCode: 'TE' },
  { nameEn: 'Rudehen', nameFa: 'رودهن', provinceCode: 'TE' },
  { nameEn: 'Absard', nameFa: 'آبسرد دماوند', provinceCode: 'TE' },
  { nameEn: 'Qaemieh', nameFa: 'قائمیه', provinceCode: 'FA' },
  { nameEn: 'Nurabad Lorestan', nameFa: 'نورآباد لرستان', provinceCode: 'LO' },
  { nameEn: 'Aleshtar', nameFa: 'الشتر', provinceCode: 'LO' },
  { nameEn: 'Delfan', nameFa: 'دلفان', provinceCode: 'LO' },
  { nameEn: 'Selseleh', nameFa: 'سلسله', provinceCode: 'LO' },
  { nameEn: 'Bastak', nameFa: 'بستک', provinceCode: 'HG' },
  { nameEn: 'Parsian', nameFa: 'پارسیان', provinceCode: 'HG' },
  { nameEn: 'Jask', nameFa: 'جاسک', provinceCode: 'HG' },
  { nameEn: 'Sirik', nameFa: 'سیریک', provinceCode: 'HG' },
  { nameEn: 'Haji Abad Hormozgan', nameFa: 'حاجی آباد هرمزگان', provinceCode: 'HG' },
  { nameEn: 'Nikshahr', nameFa: 'نیک‌شهر', provinceCode: 'SB' },
  { nameEn: 'Sarbaz', nameFa: 'سرباز', provinceCode: 'SB' },
  { nameEn: 'Mirjaveh', nameFa: 'میرجاوه', provinceCode: 'SB' },
  { nameEn: 'Dalgan', nameFa: 'دلگان', provinceCode: 'SB' },
  { nameEn: 'Fanuj', nameFa: 'فنوج', provinceCode: 'SB' },
  { nameEn: 'Nehbandan Shusf', nameFa: 'شوسف', provinceCode: 'SK' },
  { nameEn: 'Sarbisheh', nameFa: 'سربیشه', provinceCode: 'SK' },
  { nameEn: 'Darmian', nameFa: 'درمیان', provinceCode: 'SK' },
  { nameEn: 'Zirkuh', nameFa: 'زیرکوه', provinceCode: 'SK' },
  { nameEn: 'Boshruyeh', nameFa: 'بشرویه', provinceCode: 'SK' },
  { nameEn: 'Raz and Jargalan', nameFa: 'راز و جرگلان', provinceCode: 'NK' },
  { nameEn: 'Garmeh', nameFa: 'گرمه', provinceCode: 'NK' },
  { nameEn: 'Mana and Samalghan', nameFa: 'مانه و سملقان', provinceCode: 'NK' },
  { nameEn: 'Joveyn', nameFa: 'جوین', provinceCode: 'RK' },
  { nameEn: 'Joghatay', nameFa: 'جغتای', provinceCode: 'RK' },
  { nameEn: 'Firuzeh', nameFa: 'فیروزه', provinceCode: 'RK' },
  { nameEn: 'Zaveh', nameFa: 'زاوه', provinceCode: 'RK' },
  { nameEn: 'Bakharz', nameFa: 'باخرز', provinceCode: 'RK' },
  { nameEn: 'Kalat', nameFa: 'کلات', provinceCode: 'RK' },
  { nameEn: 'Dargaz Lotfabad', nameFa: 'لطف‌آباد', provinceCode: 'RK' },
  { nameEn: 'Marivan Kani Dinar', nameFa: 'کانی‌دینار', provinceCode: 'KD' },
  { nameEn: 'Saqqez Industrial', nameFa: 'شهرک صنعتی سقز', provinceCode: 'KD' },
  { nameEn: 'Dehgolan', nameFa: 'دهگلان', provinceCode: 'KD' },
  { nameEn: 'Sarvabad', nameFa: 'سروآباد', provinceCode: 'KD' },
  { nameEn: 'Zarrinabad', nameFa: 'زرین‌آباد', provinceCode: 'ZN' },
  { nameEn: 'Soltaniyeh', nameFa: 'سلطانیه', provinceCode: 'ZN' },
  { nameEn: 'Mahneshan', nameFa: 'ماهنشان', provinceCode: 'ZN' },
  { nameEn: 'Ijrud', nameFa: 'ایجرود', provinceCode: 'ZN' },
  { nameEn: 'Hidaj', nameFa: 'هیدج', provinceCode: 'ZN' },
  { nameEn: 'Sorkheh', nameFa: 'سرخه', provinceCode: 'SM' },
  { nameEn: 'Aradan', nameFa: 'آرادان', provinceCode: 'SM' },
  { nameEn: 'Mayamey', nameFa: 'میامی', provinceCode: 'SM' },
  { nameEn: 'Bastam', nameFa: 'بسطام', provinceCode: 'SM' },
  { nameEn: 'Shahmirzad', nameFa: 'شهمیرزاد', provinceCode: 'SM' },
  { nameEn: 'Azadshahr', nameFa: 'آزادشهر', provinceCode: 'GO' },
  { nameEn: 'Ramian', nameFa: 'رامیان', provinceCode: 'GO' },
  { nameEn: 'Galikash', nameFa: 'گالیکش', provinceCode: 'GO' },
  { nameEn: 'Maraveh Tappeh', nameFa: 'مراوه‌تپه', provinceCode: 'GO' },
  { nameEn: 'Bandar Gaz', nameFa: 'بندر گز', provinceCode: 'GO' },
  { nameEn: 'Namin', nameFa: 'نمین', provinceCode: 'AR' },
  { nameEn: 'Nir', nameFa: 'نیر', provinceCode: 'AR' },
  { nameEn: 'Sareyn', nameFa: 'سرعین', provinceCode: 'AR' },
  { nameEn: 'Kowsar', nameFa: 'کوثر', provinceCode: 'AR' },
  { nameEn: 'Ungut', nameFa: 'انگوت', provinceCode: 'AR' },
  { nameEn: 'Eyvaneke', nameFa: 'ایوانکی', provinceCode: 'SM' },
  { nameEn: 'Pishva Varamin', nameFa: 'پیشوا ورامین', provinceCode: 'TE' },
  { nameEn: 'Qarchak', nameFa: 'قرچک', provinceCode: 'TE' },
  { nameEn: 'Nasimshahr', nameFa: 'نسیم‌شهر', provinceCode: 'TE' },
  { nameEn: 'Salehieh', nameFa: 'صالحیه', provinceCode: 'TE' },
  { nameEn: 'Ferdowsieh', nameFa: 'فردوسیه', provinceCode: 'TE' },
  { nameEn: 'Shahedshahr', nameFa: 'شاهدشهر', provinceCode: 'TE' },
  { nameEn: 'Sabashahr', nameFa: 'صباشهر', provinceCode: 'TE' },
  { nameEn: 'Vahidieh', nameFa: 'وحیدیه', provinceCode: 'TE' },
  { nameEn: 'Baghersetan', nameFa: 'بهارستان اصفهان', provinceCode: 'IS' },
  // Gulf / nearby (kept for cross-border commerce prompts)
  { nameEn: 'Dubai', nameFa: 'دبی', provinceCode: 'AE', aliases: ['Dubai'] },
];

export const IRAN_PROVINCE_BY_CODE: Record<string, IranProvince> = Object.fromEntries(
  IRAN_PROVINCES.map((p) => [p.code, p]),
);
